name: CI

on:
  - push
  - pull_request
  
jobs:
  fetch-commit-message:
    runs-on: ubuntu-latest
    outputs:
      commit_message: ${{ steps.get_commit_message.outputs.message }}
    steps:
    - uses: actions/checkout@v2
    - name: "Fetch commit message"
      id: get_commit_message
      run: echo "message=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT

  check-no-ci:
    runs-on: ubuntu-latest
    needs: fetch-commit-message
    outputs:
      no_ci: ${{ steps.check_no_ci.outputs.no_ci }}
    steps:
    - name: "Check for [no_ci] in commit message"
      id: check_no_ci
      run: |
        if echo "${{ needs.fetch-commit-message.outputs.commit_message }}" | grep -iq '\[no_ci\]'; then
          echo "no_ci=true" >> $GITHUB_OUTPUT
        else
          echo "no_ci=false" >> $GITHUB_OUTPUT
        fi

  spellcheck:
    runs-on: ubuntu-latest
    needs: check-no-ci
    if: needs.check-no-ci.outputs.no_ci == 'false'
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: Install codespell
        shell: bash
        run: |
          sudo apt-get update || true
          sudo apt-get install -y codespell
      - name: Run Spellchecker
        run: codespell

  sort-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Set up Python"
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: "Sort README.md's"
        run: python ./lone_sort_readme.py
        
      - name: "Commit results"
        run: |
          git config --global user.email ""
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Sort README.md's" || echo "Nothing to commit"
          git push || echo "Nothing to push"
